name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install `yasm`
        run: sudo apt-get update && sudo apt-get install build-essential yasm -y

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo bin
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Install `cargo` tools to do more testing
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,cargo-nextest,cargo-rdme

      - name: Run tests
        run: cargo nextest run

      - name: Run doctests
        run: cargo test --doc

      - name: Check for unused dependencies
        uses: bnjbvr/cargo-machete@main

  cargo_deny:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install `cargo` tools to do more testing
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny


  readme:
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4

      - name: Install `yasm`
        run: sudo apt-get update && sudo apt-get install build-essential yasm -y

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install `cargo` tools to do more testing
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-rdme

      - name: Make sure README is up-to-date
        run: cargo rdme --check