name: Backdrop CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install an assembler
        run: sudo apt-get install yasm -y

      # install required system dependencies
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.44.0
          cache: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo bin
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: pixi run build

      - name: Install `cargo` tools to do more testing
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,cargo-machete,cargo-nextest,cargo-rdme

      - name: Run checks
        run: pixi run check
